    // Muscle Grid Styles
    muscleGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginHorizontal: -4,
    },
    muscleGridItem: {
      width: '33.33%',
      padding: 4,
      alignItems: 'center',
    },
    muscleGridItemInner: {
      width: '100%',
      alignItems: 'center',
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    muscleGridItemSelected: {
      backgroundColor: isDarkMode ? '#1C1C1E' : '#F3F4F6',
      borderColor: colors.brandPrimary,
    },
    muscleBodyContainer: {
      width: 74,
      height: 74,
      borderRadius: 12,
      backgroundColor: isDarkMode ? '#1C1C1E' : '#F3F4F6',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
      marginBottom: 8,
    },
    muscleBodyWrapper: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      width: 120,
      height: 240,
      marginTop: -120,
      marginLeft: -60,
      alignItems: 'center',
      justifyContent: 'center',
    },
    muscleGridItemLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.textPrimary,
      textAlign: 'center',
    },

    // Muscle List Styles
    muscleList: {
      marginTop: 8,
    },
    muscleListItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    muscleListItemBody: {
      width: 60,
      height: 60,
      borderRadius: 8,
      backgroundColor: isDarkMode ? '#1C1C1E' : '#F3F4F6',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
      marginRight: 16,
    },
    muscleListItemLabel: {
      flex: 1,
      fontSize: 16,
      fontWeight: '500',
      color: colors.textPrimary,
    },
    stepperContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDarkMode ? '#1C1C1E' : '#F3F4F6',
      borderRadius: 20,
      paddingHorizontal: 4,
      paddingVertical: 4,
    },
    stepperButton: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
    },
    stepperValue: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textPrimary,
      marginHorizontal: 12,
      minWidth: 12,
      textAlign: 'center',
    },