-- Allow followers to view routines
-- Generated by Antigravity

-- 1. Drop existing select policies
drop policy if exists workout_routines_select on public.workout_routines;
drop policy if exists workout_routine_exercises_select on public.workout_routine_exercises;
drop policy if exists workout_routine_sets_select on public.workout_routine_sets;

-- 2. Create new select policies

-- Routines: Owner or Follower
create policy workout_routines_select on public.workout_routines
  for select
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.follows
      where follower_id = auth.uid()
      and followee_id = workout_routines.user_id
    )
  );

-- Routine Exercises: If you can see the routine
create policy workout_routine_exercises_select on public.workout_routine_exercises
  for select
  using (exists (
    select 1
    from public.workout_routines r
    where r.id = routine_id
      and (
        r.user_id = auth.uid()
        or exists (
          select 1 from public.follows
          where follower_id = auth.uid()
          and followee_id = r.user_id
        )
      )
  ));

-- Routine Sets: If you can see the routine exercise (which implies seeing the routine)
create policy workout_routine_sets_select on public.workout_routine_sets
  for select
  using (exists (
    select 1
    from public.workout_routine_exercises e
    join public.workout_routines r on r.id = e.routine_id
    where e.id = routine_exercise_id
      and (
        r.user_id = auth.uid()
        or exists (
          select 1 from public.follows
          where follower_id = auth.uid()
          and followee_id = r.user_id
        )
      )
  ));
