-- Enable row level security and define policies for social tables
-- Generated by GPT-5 Codex, 2025-11-13

-- Enable RLS on new tables
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_comments ENABLE ROW LEVEL SECURITY;

-- Follow table policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'follows'
      AND policyname = 'Follow relationships are viewable by everyone'
  ) THEN
    CREATE POLICY "Follow relationships are viewable by everyone"
      ON follows
      FOR SELECT
      USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'follows'
      AND policyname = 'Users can follow others'
  ) THEN
    CREATE POLICY "Users can follow others"
      ON follows
      FOR INSERT
      WITH CHECK (auth.uid() = follower_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'follows'
      AND policyname = 'Users can unfollow others'
  ) THEN
    CREATE POLICY "Users can unfollow others"
      ON follows
      FOR DELETE
      USING (auth.uid() = follower_id);
  END IF;
END $$;

-- Workout likes policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'workout_likes'
      AND policyname = 'Workout likes are viewable by everyone'
  ) THEN
    CREATE POLICY "Workout likes are viewable by everyone"
      ON workout_likes
      FOR SELECT
      USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'workout_likes'
      AND policyname = 'Users can like workouts'
  ) THEN
    CREATE POLICY "Users can like workouts"
      ON workout_likes
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'workout_likes'
      AND policyname = 'Users can remove their likes'
  ) THEN
    CREATE POLICY "Users can remove their likes"
      ON workout_likes
      FOR DELETE
      USING (auth.uid() = user_id);
  END IF;
END $$;

-- Workout comments policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'workout_comments'
      AND policyname = 'Workout comments are viewable by everyone'
  ) THEN
    CREATE POLICY "Workout comments are viewable by everyone"
      ON workout_comments
      FOR SELECT
      USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'workout_comments'
      AND policyname = 'Users can insert their own comments'
  ) THEN
    CREATE POLICY "Users can insert their own comments"
      ON workout_comments
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'workout_comments'
      AND policyname = 'Users can update their own comments'
  ) THEN
    CREATE POLICY "Users can update their own comments"
      ON workout_comments
      FOR UPDATE
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'workout_comments'
      AND policyname = 'Workout owners can delete comments on their workouts'
  ) THEN
    CREATE POLICY "Workout owners can delete comments on their workouts"
      ON workout_comments
      FOR DELETE
      USING (
        auth.uid() = user_id OR
        EXISTS (
          SELECT 1
          FROM workout_sessions ws
          WHERE ws.id = workout_comments.workout_id
            AND ws.user_id = auth.uid()
        )
      );
  END IF;
END $$;

-- Helper SQL functions for follower counts
CREATE OR REPLACE FUNCTION public.follower_count(target_user UUID)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
  SELECT COUNT(*)
  FROM follows
  WHERE followee_id = target_user;
$$;

CREATE OR REPLACE FUNCTION public.following_count(target_user UUID)
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
  SELECT COUNT(*)
  FROM follows
  WHERE follower_id = target_user;
$$;


