-- Create social relationship tables for follows, likes, and comments
-- Generated by GPT-5 Codex, 2025-11-13

-- Create follows table (Strava-style social graph)
CREATE TABLE IF NOT EXISTS follows (
  follower_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  followee_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT follows_pkey PRIMARY KEY (follower_id, followee_id),
  CONSTRAINT follows_prevent_self_follow CHECK (follower_id <> followee_id)
);

-- Indexes to support "who do I follow?" and "who follows me?" lookups
CREATE INDEX IF NOT EXISTS idx_follows_follower_id ON follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_followee_id ON follows(followee_id);

-- Create table for workout likes
CREATE TABLE IF NOT EXISTS workout_likes (
  workout_id UUID NOT NULL REFERENCES workout_sessions(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT workout_likes_pkey PRIMARY KEY (workout_id, user_id)
);

-- Index to quickly fetch likes by user
CREATE INDEX IF NOT EXISTS idx_workout_likes_user_id ON workout_likes(user_id);

-- Create table for workout comments
CREATE TABLE IF NOT EXISTS workout_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workout_id UUID NOT NULL REFERENCES workout_sessions(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (length(trim(content)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Keep updated_at in sync on modifications
CREATE TRIGGER workout_comments_set_updated_at
  BEFORE UPDATE ON workout_comments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- Indexes for common access patterns
CREATE INDEX IF NOT EXISTS idx_workout_comments_workout_id ON workout_comments(workout_id);
CREATE INDEX IF NOT EXISTS idx_workout_comments_user_id ON workout_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_workout_comments_created_at ON workout_comments(created_at DESC);

-- Helper view to expose aggregated social metadata per workout
CREATE OR REPLACE VIEW workout_social_stats AS
SELECT
  ws.id AS workout_id,
  COALESCE(like_counts.like_count, 0) AS like_count,
  COALESCE(comment_counts.comment_count, 0) AS comment_count
FROM workout_sessions ws
LEFT JOIN (
  SELECT workout_id, COUNT(*) AS like_count
  FROM workout_likes
  GROUP BY workout_id
) like_counts
  ON like_counts.workout_id = ws.id
LEFT JOIN (
  SELECT workout_id, COUNT(*) AS comment_count
  FROM workout_comments
  GROUP BY workout_id
) comment_counts
  ON comment_counts.workout_id = ws.id;


