-- Add comprehensive exercise library with common variations
INSERT INTO exercises (name, muscle_group, type, equipment, aliases) VALUES
  -- CHEST
  ('Decline Bench Press', 'Chest', 'compound', 'barbell', ARRAY['decline bench', 'decline press', 'decline barbell bench']),
  ('Decline Dumbbell Bench Press', 'Chest', 'compound', 'dumbbell', ARRAY['decline db bench', 'decline dumbbell press']),
  ('Incline Dumbbell Bench Press', 'Chest', 'compound', 'dumbbell', ARRAY['incline db bench', 'incline dumbbell press']),
  ('Incline Dumbbell Fly', 'Chest', 'isolation', 'dumbbell', ARRAY['incline fly', 'incline flyes', 'incline dumbbell flyes']),
  ('Decline Dumbbell Fly', 'Chest', 'isolation', 'dumbbell', ARRAY['decline fly', 'decline flyes']),
  ('Cable Crossover', 'Chest', 'isolation', 'cable', ARRAY['cable cross', 'cable fly crossover', 'crossover']),
  ('Pec Deck', 'Chest', 'isolation', 'machine', ARRAY['pec deck fly', 'pec deck machine', 'butterfly', 'pec fly machine']),
  ('Machine Chest Press', 'Chest', 'compound', 'machine', ARRAY['machine chest', 'chest press machine', 'chest machine press']),
  ('Landmine Press', 'Chest', 'compound', 'barbell', ARRAY['landmine chest press', 'landmine press']),

  -- BACK
  ('Single Arm Dumbbell Row', 'Back', 'compound', 'dumbbell', ARRAY['one arm row', 'one arm db row', 'single arm db row', 'single arm dumbbell row']),
  ('Pendlay Row', 'Back', 'compound', 'barbell', ARRAY['pendlay rows', 'dead stop row']),
  ('Chest Supported Row', 'Back', 'compound', 'dumbbell', ARRAY['incline row', 'supported row', 'incline db row']),
  ('Dumbbell Pullover', 'Back', 'isolation', 'dumbbell', ARRAY['pullover', 'pullovers', 'db pullover']),
  ('Cable Pullover', 'Back', 'isolation', 'cable', ARRAY['straight arm pulldown', 'cable pullovers']),
  ('Barbell Shrug', 'Back', 'isolation', 'barbell', ARRAY['bb shrug', 'trap shrug', 'barbell shrugs']),
  ('Dumbbell Shrug', 'Back', 'isolation', 'dumbbell', ARRAY['db shrug', 'dumbbell shrugs', 'db shrugs']),
  ('Rack Pull', 'Back', 'compound', 'barbell', ARRAY['rack pulls', 'rack deadlift']),
  ('Sumo Deadlift', 'Back', 'compound', 'barbell', ARRAY['sumo dl', 'sumo']),
  ('Seal Row', 'Back', 'compound', 'barbell', ARRAY['seal rows']),
  ('Meadows Row', 'Back', 'compound', 'barbell', ARRAY['landmine row', 'meadows rows']),
  ('Wide Grip Lat Pulldown', 'Back', 'compound', 'cable', ARRAY['wide lat pulldown', 'wide grip pulldown', 'wide grip lat pull']),
  ('Close Grip Lat Pulldown', 'Back', 'compound', 'cable', ARRAY['close grip lat pulldown', 'narrow grip pulldown', 'narrow lat pulldown']),
  ('Underhand Lat Pulldown', 'Back', 'compound', 'cable', ARRAY['supinated pulldown', 'reverse grip pulldown', 'underhand pulldown']),
  ('Reverse Fly', 'Back', 'isolation', 'dumbbell', ARRAY['rear delt fly', 'reverse flyes', 'bent over reverse fly', 'rear delt flyes']),
  ('Cable Reverse Fly', 'Back', 'isolation', 'cable', ARRAY['cable rear delt fly', 'cable reverse flyes']),
  ('Machine Row', 'Back', 'compound', 'machine', ARRAY['machine rows', 'seated machine row']),
  ('Inverted Row', 'Back', 'compound', 'bodyweight', ARRAY['australian pullup', 'bodyweight row', 'inverted rows']),
  ('Chin-ups', 'Back', 'compound', 'bodyweight', ARRAY['chin up', 'chinup', 'chinups', 'underhand pullup']),

  -- LEGS - QUADS
  ('Hack Squat', 'Legs', 'compound', 'machine', ARRAY['hack squats', 'hack squat machine']),
  ('Goblet Squat', 'Legs', 'compound', 'dumbbell', ARRAY['goblet squats', 'kettlebell squat']),
  ('Walking Lunge', 'Legs', 'compound', 'bodyweight', ARRAY['walking lunges', 'forward lunge']),
  ('Reverse Lunge', 'Legs', 'compound', 'bodyweight', ARRAY['reverse lunges', 'backward lunge']),
  ('Step Up', 'Legs', 'compound', 'bodyweight', ARRAY['step ups', 'box step up', 'box step ups']),
  ('Sissy Squat', 'Legs', 'isolation', 'bodyweight', ARRAY['sissy squats']),
  ('Box Squat', 'Legs', 'compound', 'barbell', ARRAY['box squats']),
  ('Safety Bar Squat', 'Legs', 'compound', 'barbell', ARRAY['ssb squat', 'safety squat bar']),

  -- LEGS - HAMSTRINGS
  ('Nordic Curl', 'Legs', 'isolation', 'bodyweight', ARRAY['nordic curls', 'nordic hamstring curl', 'nordics']),
  ('Swiss Ball Leg Curl', 'Legs', 'isolation', 'bodyweight', ARRAY['stability ball curl', 'physio ball curl']),
  ('Single Leg Romanian Deadlift', 'Legs', 'compound', 'dumbbell', ARRAY['single leg rdl', 'one leg rdl', 'sldl']),
  ('Good Morning', 'Legs', 'compound', 'barbell', ARRAY['good mornings', 'barbell good morning']),
  ('Seated Leg Curl', 'Legs', 'isolation', 'machine', ARRAY['seated hamstring curl', 'seated leg curls']),
  ('Lying Leg Curl', 'Legs', 'isolation', 'machine', ARRAY['lying hamstring curl', 'prone leg curl']),
  ('Standing Leg Curl', 'Legs', 'isolation', 'machine', ARRAY['standing hamstring curl']),

  -- GLUTES
  ('Single Leg Glute Bridge', 'Glutes', 'isolation', 'bodyweight', ARRAY['single leg bridge', 'one leg bridge']),
  ('Barbell Glute Bridge', 'Glutes', 'compound', 'barbell', ARRAY['barbell bridge', 'bb glute bridge']),
  ('Donkey Kick', 'Glutes', 'isolation', 'bodyweight', ARRAY['donkey kicks', 'quadruped hip extension']),
  ('Fire Hydrant', 'Glutes', 'isolation', 'bodyweight', ARRAY['fire hydrants', 'quadruped hip abduction']),
  ('Banded Lateral Walk', 'Glutes', 'isolation', 'bands', ARRAY['monster walk', 'band walk', 'side walk']),
  ('Deficit Deadlift', 'Glutes', 'compound', 'barbell', ARRAY['deficit dl', 'deficit deadlifts']),
  ('B-Stance Hip Thrust', 'Glutes', 'compound', 'barbell', ARRAY['kickstand hip thrust', 'staggered hip thrust']),
  ('Frog Pump', 'Glutes', 'isolation', 'bodyweight', ARRAY['frog pumps', 'frog glute bridge']),

  -- CALVES
  ('Standing Calf Raise', 'Calves', 'isolation', 'machine', ARRAY['calf raise', 'standing calves', 'standing calf raises']),
  ('Seated Calf Raise', 'Calves', 'isolation', 'machine', ARRAY['seated calves', 'seated calf raises']),
  ('Donkey Calf Raise', 'Calves', 'isolation', 'machine', ARRAY['donkey calves', 'donkey calf raises']),
  ('Single Leg Calf Raise', 'Calves', 'isolation', 'bodyweight', ARRAY['one leg calf raise', 'single calf raise']),

  -- SHOULDERS
  ('Rear Delt Fly', 'Shoulders', 'isolation', 'dumbbell', ARRAY['rear delt flyes', 'reverse delt fly', 'bent over lateral raise']),
  ('Upright Row', 'Shoulders', 'compound', 'barbell', ARRAY['upright rows', 'barbell upright row']),
  ('Cable Lateral Raise', 'Shoulders', 'isolation', 'cable', ARRAY['cable side raise', 'cable lateral raises']),
  ('Machine Shoulder Press', 'Shoulders', 'compound', 'machine', ARRAY['shoulder press machine', 'machine shoulder']),
  ('Behind the Neck Press', 'Shoulders', 'compound', 'barbell', ARRAY['btn press', 'behind neck press']),
  ('Push Press', 'Shoulders', 'compound', 'barbell', ARRAY['push press', 'push jerk']),
  ('Dumbbell Upright Row', 'Shoulders', 'compound', 'dumbbell', ARRAY['db upright row']),
  ('Cable Front Raise', 'Shoulders', 'isolation', 'cable', ARRAY['cable front raises']),
  ('Cable Rear Delt Fly', 'Shoulders', 'isolation', 'cable', ARRAY['cable rear delt flyes', 'cable reverse fly']),
  ('Machine Lateral Raise', 'Shoulders', 'isolation', 'machine', ARRAY['machine side raise']),
  ('Barbell Front Raise', 'Shoulders', 'isolation', 'barbell', ARRAY['barbell front raises']),
  ('Y Raise', 'Shoulders', 'isolation', 'dumbbell', ARRAY['y raises', 'incline y raise']),
  ('W Raise', 'Shoulders', 'isolation', 'dumbbell', ARRAY['w raises']),

  -- BICEPS
  ('Preacher Curl', 'Biceps', 'isolation', 'barbell', ARRAY['preacher curls', 'barbell preacher curl', 'ez bar preacher curl']),
  ('Dumbbell Preacher Curl', 'Biceps', 'isolation', 'dumbbell', ARRAY['db preacher curl', 'dumbbell preacher curls']),
  ('Concentration Curl', 'Biceps', 'isolation', 'dumbbell', ARRAY['concentration curls', 'seated concentration curl']),
  ('Cable Curl', 'Biceps', 'isolation', 'cable', ARRAY['cable curls', 'cable bicep curl']),
  ('Incline Dumbbell Curl', 'Biceps', 'isolation', 'dumbbell', ARRAY['incline curl', 'incline db curl']),
  ('Reverse Curl', 'Biceps', 'isolation', 'barbell', ARRAY['reverse curls', 'reverse barbell curl', 'reverse grip barbell curl']),
  ('Spider Curl', 'Biceps', 'isolation', 'barbell', ARRAY['spider curls', 'prone curl']),
  ('Zottman Curl', 'Biceps', 'isolation', 'dumbbell', ARRAY['zottman curls']),
  ('EZ Bar Curl', 'Biceps', 'isolation', 'barbell', ARRAY['ez curl', 'ez bar curls', 'easy bar curl']),
  ('Cable Hammer Curl', 'Biceps', 'isolation', 'cable', ARRAY['rope hammer curl', 'cable hammer curls']),
  ('Cross Body Hammer Curl', 'Biceps', 'isolation', 'dumbbell', ARRAY['cross body curl', 'pinwheel curl']),

  -- TRICEPS
  ('Overhead Tricep Extension', 'Triceps', 'isolation', 'dumbbell', ARRAY['dumbbell overhead extension', 'tricep overhead extension', 'db overhead extension']),
  ('Cable Overhead Tricep Extension', 'Triceps', 'isolation', 'cable', ARRAY['cable overhead tricep extension', 'rope overhead extension', 'cable overhead extension']),
  ('Diamond Push-up', 'Triceps', 'compound', 'bodyweight', ARRAY['diamond pushup', 'diamond pushups', 'diamond push ups']),
  ('Tricep Kickback', 'Triceps', 'isolation', 'dumbbell', ARRAY['tricep kickbacks', 'dumbbell kickback', 'db kickback']),
  ('French Press', 'Triceps', 'isolation', 'barbell', ARRAY['lying tricep extension', 'french press']),
  ('Rope Pushdown', 'Triceps', 'isolation', 'cable', ARRAY['rope tricep pushdown', 'rope extension']),
  ('Single Arm Cable Pushdown', 'Triceps', 'isolation', 'cable', ARRAY['one arm pushdown', 'single arm tricep pushdown']),
  ('Overhead Cable Tricep Extension', 'Triceps', 'isolation', 'cable', ARRAY['overhead cable extension']),
  ('Dumbbell Skull Crusher', 'Triceps', 'isolation', 'dumbbell', ARRAY['db skull crusher', 'dumbbell lying tricep extension']),
  ('Close Grip Push-up', 'Triceps', 'compound', 'bodyweight', ARRAY['close grip pushup', 'narrow pushup']),
  ('Tate Press', 'Triceps', 'isolation', 'dumbbell', ARRAY['tate press']),

  -- CORE
  ('Cable Crunch', 'Core', 'isolation', 'cable', ARRAY['cable crunches', 'kneeling cable crunch']),
  ('Bicycle Crunch', 'Core', 'isolation', 'bodyweight', ARRAY['bicycle crunches', 'bicycle']),
  ('Mountain Climber', 'Core', 'compound', 'bodyweight', ARRAY['mountain climbers']),
  ('Side Plank', 'Core', 'isolation', 'bodyweight', ARRAY['side planks', 'lateral plank']),
  ('Dead Bug', 'Core', 'isolation', 'bodyweight', ARRAY['deadbug', 'dead bugs']),
  ('Bird Dog', 'Core', 'isolation', 'bodyweight', ARRAY['birddog', 'bird dogs']),
  ('Pallof Press', 'Core', 'isolation', 'cable', ARRAY['pallof', 'pallof press']),
  ('Cable Woodchopper', 'Core', 'compound', 'cable', ARRAY['woodchop', 'wood chopper', 'cable chop']),
  ('Decline Sit-up', 'Core', 'isolation', 'bodyweight', ARRAY['decline situp', 'decline crunches']),
  ('Toe Touch', 'Core', 'isolation', 'bodyweight', ARRAY['toe touches', 'lying toe touch']),
  ('V-up', 'Core', 'isolation', 'bodyweight', ARRAY['v ups', 'jackknife']),
  ('Hollow Hold', 'Core', 'isolation', 'bodyweight', ARRAY['hollow body hold', 'hollow rocks']),
  ('L-Sit', 'Core', 'isolation', 'bodyweight', ARRAY['l sit', 'l-sits']),
  ('Windshield Wiper', 'Core', 'isolation', 'bodyweight', ARRAY['windshield wipers', 'hanging windshield wiper']),
  ('Dragon Flag', 'Core', 'compound', 'bodyweight', ARRAY['dragon flags']),
  ('Leg Raise', 'Core', 'isolation', 'bodyweight', ARRAY['leg raises', 'lying leg raise']),

  -- FOREARMS
  ('Wrist Curl', 'Forearms', 'isolation', 'barbell', ARRAY['wrist curls', 'barbell wrist curl', 'forearm curl']),
  ('Reverse Wrist Curl', 'Forearms', 'isolation', 'barbell', ARRAY['reverse wrist curls', 'reverse forearm curl']),
  ('Farmer Walk', 'Forearms', 'compound', 'dumbbell', ARRAY['farmers walk', 'farmers carry', 'farmer carry']),
  ('Dead Hang', 'Forearms', 'isolation', 'bodyweight', ARRAY['dead hangs', 'bar hang']),
  ('Plate Pinch', 'Forearms', 'isolation', 'equipment', ARRAY['plate pinch hold', 'pinch grip']),
  ('Dumbbell Wrist Curl', 'Forearms', 'isolation', 'dumbbell', ARRAY['db wrist curl', 'db wrist curls']),

  -- OLYMPIC / FULL BODY
  ('Clean', 'Full Body', 'compound', 'barbell', ARRAY['barbell clean', 'full clean']),
  ('Clean and Jerk', 'Full Body', 'compound', 'barbell', ARRAY['clean & jerk', 'clean jerk']),
  ('Snatch', 'Full Body', 'compound', 'barbell', ARRAY['barbell snatch', 'full snatch']),
  ('Power Clean', 'Full Body', 'compound', 'barbell', ARRAY['powerclean', 'power cleans']),
  ('Hang Clean', 'Full Body', 'compound', 'barbell', ARRAY['hang cleans', 'hanging clean']),
  ('Thruster', 'Full Body', 'compound', 'barbell', ARRAY['thrusters', 'squat press']),
  ('Burpee', 'Full Body', 'compound', 'bodyweight', ARRAY['burpees', 'burpee jump']),
  ('Box Jump', 'Full Body', 'compound', 'bodyweight', ARRAY['box jumps', 'jump box']),
  ('Jump Squat', 'Full Body', 'compound', 'bodyweight', ARRAY['jump squats', 'squat jump']),
  ('Kettlebell Swing', 'Full Body', 'compound', 'kettlebell', ARRAY['kb swing', 'russian swing', 'kettlebell swings']),
  ('Turkish Get-up', 'Full Body', 'compound', 'kettlebell', ARRAY['tgu', 'turkish getup', 'get up']),
  ('Man Maker', 'Full Body', 'compound', 'dumbbell', ARRAY['manmaker', 'man makers']),
  ('Wall Ball', 'Full Body', 'compound', 'medicine ball', ARRAY['wall balls', 'wallball']),
  ('Sled Push', 'Full Body', 'compound', 'equipment', ARRAY['prowler push', 'sled pushes']),
  ('Sled Pull', 'Full Body', 'compound', 'equipment', ARRAY['prowler pull', 'sled pulls']),
  ('Battle Rope', 'Full Body', 'compound', 'equipment', ARRAY['battle ropes', 'rope waves']),

  -- CARDIO
  ('Running', 'Cardio', 'cardio', 'bodyweight', ARRAY['run', 'jog', 'jogging', 'treadmill']),
  ('Cycling', 'Cardio', 'cardio', 'equipment', ARRAY['bike', 'biking', 'stationary bike', 'spin']),
  ('Rowing', 'Cardio', 'cardio', 'machine', ARRAY['row machine', 'erg', 'concept 2', 'rower']),
  ('Elliptical', 'Cardio', 'cardio', 'machine', ARRAY['elliptical machine']),
  ('Stairmaster', 'Cardio', 'cardio', 'machine', ARRAY['stair master', 'stair climber', 'stepmill']),
  ('Jump Rope', 'Cardio', 'cardio', 'equipment', ARRAY['jump rope', 'skipping', 'skipping rope', 'double unders']),
  ('Swimming', 'Cardio', 'cardio', 'bodyweight', ARRAY['swim', 'swimming laps']),
  ('Assault Bike', 'Cardio', 'cardio', 'machine', ARRAY['air bike', 'assault air bike', 'echo bike']),
  ('Ski Erg', 'Cardio', 'cardio', 'machine', ARRAY['ski machine', 'ski erg machine']),
  ('Incline Walk', 'Cardio', 'cardio', 'machine', ARRAY['incline walking', 'treadmill incline walk', 'incline treadmill'])

ON CONFLICT (name) DO NOTHING;
