-- Proactive coach opener messages generated by the hourly scheduler.

CREATE TABLE IF NOT EXISTS public.proactive_coach_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trigger_type TEXT NOT NULL CHECK (
    trigger_type IN (
      'workout_day_morning',
      'missed_workout',
      'comeback',
      'post_workout_followup'
    )
  ),
  coach_id TEXT NOT NULL,
  body TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  consumed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS proactive_coach_messages_user_unconsumed_idx
  ON public.proactive_coach_messages (user_id, created_at DESC)
  WHERE consumed_at IS NULL;

ALTER TABLE public.proactive_coach_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "owner can read own" ON public.proactive_coach_messages;
CREATE POLICY "owner can read own"
  ON public.proactive_coach_messages
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "owner can mark consumed" ON public.proactive_coach_messages;
CREATE POLICY "owner can mark consumed"
  ON public.proactive_coach_messages
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.retention_push_preferences
  ADD COLUMN IF NOT EXISTS proactive_coach_enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE public.notifications
  DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE public.notifications
  ADD CONSTRAINT notifications_type_check CHECK (
    type IN (
      'workout_like',
      'workout_comment',
      'workout_comment_reply',
      'workout_comment_like',
      'followed_workout_post',
      'follow_request_received',
      'follow_request_approved',
      'follow_request_declined',
      'follow_received',
      'trial_reminder',
      'retention_scheduled_workout',
      'retention_streak_protection',
      'retention_inactivity',
      'retention_weekly_recap',
      'retention_milestone',
      'proactive_coach_workout_day_morning',
      'proactive_coach_missed_workout',
      'proactive_coach_comeback',
      'proactive_coach_post_workout_followup'
    )
  );

CREATE OR REPLACE FUNCTION public.invoke_proactive_coach_scheduler()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  project_url TEXT;
  service_role_key TEXT;
  retention_secret TEXT;
  request_headers JSONB;
BEGIN
  SELECT decrypted_secret
  INTO project_url
  FROM vault.decrypted_secrets
  WHERE name IN ('project_url', 'supabase_url')
  ORDER BY CASE name WHEN 'project_url' THEN 0 ELSE 1 END
  LIMIT 1;

  IF project_url IS NULL OR project_url = '' THEN
    RAISE EXCEPTION 'Missing vault secret: project_url (or supabase_url).';
  END IF;

  SELECT decrypted_secret
  INTO service_role_key
  FROM vault.decrypted_secrets
  WHERE name IN ('service_role_key', 'supabase_service_role_key')
  ORDER BY CASE name WHEN 'service_role_key' THEN 0 ELSE 1 END
  LIMIT 1;

  IF service_role_key IS NULL OR service_role_key = '' THEN
    RAISE EXCEPTION 'Missing vault secret: service_role_key (or supabase_service_role_key).';
  END IF;

  SELECT decrypted_secret
  INTO retention_secret
  FROM vault.decrypted_secrets
  WHERE name = 'retention_scheduler_secret'
  LIMIT 1;

  IF retention_secret IS NULL OR retention_secret = '' THEN
    RAISE EXCEPTION 'Missing vault secret: retention_scheduler_secret.';
  END IF;

  IF RIGHT(project_url, 1) = '/' THEN
    project_url := LEFT(project_url, LENGTH(project_url) - 1);
  END IF;

  request_headers := jsonb_build_object(
    'Content-Type', 'application/json',
    'Authorization', 'Bearer ' || service_role_key,
    'x-retention-secret', retention_secret
  );

  PERFORM net.http_post(
    url := project_url || '/functions/v1/send-proactive-coach-messages',
    headers := request_headers,
    body := jsonb_build_object('dryRun', false)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.invoke_proactive_coach_scheduler() FROM PUBLIC;

DO $$
DECLARE
  existing_job_id BIGINT;
BEGIN
  SELECT jobid
  INTO existing_job_id
  FROM cron.job
  WHERE jobname = 'proactive-coach-hourly'
  LIMIT 1;

  IF existing_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(existing_job_id);
  END IF;
END;
$$;

SELECT cron.schedule(
  'proactive-coach-hourly',
  '8 * * * *',
  $$SELECT public.invoke_proactive_coach_scheduler();$$
);
